### ISSUE TITLE
Seems to be some case sensitivity in the multiple assignee stuff

### ISSUE THREAD

**Issue by anthlam** [thinkthroughmath/dev_wizard#48]
Folks who's actual github username (TanookiMario, MandaBrown) has capital letters in them, can show up in the assignee list twice if they are assigned to a PR by the comment posted by jenkins and are also the person set as the assignee.

Maybe the fix for this one is to make our PR assign hipchat command use the new multiple assignee feature in github, and change dev wizard to only look at the github assignees (assuming dev wizard is doing some kind of fun merging of actual assignees and users in the special jenkins assignment comment)

**Comment by joelmccracken** [comment]
Agreed -- although I think this one requires some additional semantics
around the whole assignment bit. I think it would make sense to get rid of
the json hash thing in the assignment comment, or at least use the GH
assignments at some point.

In general, we need to be able to tell:
- who is assigned to a task (who are we waiting on)
- who is assigned for code review (so that if it gets bounced around in
  QA/CR, we can tell who needs to re-review)
- who has not yet done a review

... etc. After thinking it through, I kinda think we really need some other
source of data. It may be that assignees is the best way to go about
displaying this information on github, though.

**Comment by joelmccracken** [comment]
After thinking, I think the best bet would be to just filter out duplicate
names, for now.
